- Try to fix 32 bit compilation. D:\a\gzdoom\gzdoom\src\common\platform\win32\win32vulkanvideo.h(40,1): error C2440: 'initializing': cannot convert from 'nullptr' to 'VkSurfaceKHR' (compiling source file D:\a\gzdoom\gzdoom\src\common\platform\win32\hardware.cpp) [D:\a\gzdoom\gzdoom\build\src\zdoom.vcxproj]